site_name: DataDots
site_url: https://datadots.com.br
site_description: An awesome project 
site_author: Willian Moreira

# Choose a theme
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets


# Define the navigation structure
nav:
  - Home: index.md
  - Spark: spark/intro-spark.md

# Plugins (optional)
plugins:
  - search
  - mkdocstrings

# Extra options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/willianmrs/datadots
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/yourusername

# Google Analytics (optional)
# google_analytics:
#   - UA-XXXXX-X
#   - auto

# Repository
repo_name: willianmrs/datadots
repo_url: https://github.com/willianmrs/datadots
# edit_uri: blob/master/docs/
